"""kc — mechanical maintenance CLI for a knowledge-core ecosystem.

Deterministic, model-agnostic plumbing that any agent or git hook can call.
This file is the engine seed; it currently operates on a single MODULE
(a folder of markdown, usually its own git repo). Cross-repo subcommands
(pull-all, registry, commit-push, compact-log, bootstrap, ensure-wrappers,
check-drafts) are added in later increments.

  python -m kc index [DIR]       regenerate DIR/index.md
  python -m kc lint  [DIR] [-v]  frontmatter + broken intra-module [[links]] + index freshness
  python -m kc check [DIR]       index + lint -v

DIR defaults to the current directory. Links are intra-module only by design:
there are no cross-module links in this ecosystem.
"""
import io
import re
import sys
from pathlib import Path, PurePosixPath
from collections import defaultdict

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

LINK = re.compile(r"\[\[([^\]|#]*?)\\?(#[^\]|]*)?(\\?\|[^\]]*)?\]\]")
REQUIRED = ("title", "type", "updated")
SKIP_DIRS = (".git", ".claude", ".cursor", ".obsidian", "node_modules", "__pycache__")
SKIP_FILES = ("index.md", "log.md", "CLAUDE.md", "AGENTS.md")
INDEX_HEADER = "<!-- generated by `kc index` — do not edit by hand -->"


def md_files(root):
    out = []
    for p in root.rglob("*.md"):
        if any(part in SKIP_DIRS for part in p.relative_to(root).parts):
            continue
        out.append(p)
    return out


def frontmatter(text):
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    kv = {}
    for line in text[3:end].splitlines():
        m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if m:
            kv[m.group(1)] = m.group(2).strip().strip("\"'")
    return kv


def summary_line(text):
    """First meaningful prose line after frontmatter / TL;DR heading."""
    body = text
    if text.startswith("---"):
        end = text.find("\n---", 3)
        body = text[end + 4:] if end >= 0 else text
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith(("#", ">", "|", "```", "<", "---")):
            continue
        s = re.sub(r"^\*\*TL;DR\*\*\s*[—:-]?\s*", "", s)
        s = re.sub(r"\[\[([^\]|]*\|)?([^\]]*)\]\]", r"\2", s)
        s = s.replace("**", "").replace("`", "")
        return (s[:157] + "…") if len(s) > 160 else s
    return ""


def norm(path):
    out = []
    for x in path.split("/"):
        if x in ("", "."):
            continue
        if x == "..":
            if not out:
                return None
            out.pop()
        else:
            out.append(x)
    return "/".join(out)


def build_index(root):
    groups = defaultdict(list)
    for p in sorted(md_files(root)):
        r = p.relative_to(root).as_posix()
        if PurePosixPath(r).name in SKIP_FILES:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        fm = frontmatter(text) or {}
        title = fm.get("title") or p.stem
        group = str(PurePosixPath(r).parent)
        s = summary_line(text)
        groups["." if group == "." else group].append(
            f"- [[{r[:-3]}|{title}]]" + (f" — {s}" if s else "")
        )
    name = root.resolve().name
    lines = [INDEX_HEADER, "", f"# {name} — index", ""]
    for g in sorted(groups, key=lambda x: (x != ".", x)):
        lines += [f'## {"(root)" if g == "." else g}', ""] + groups[g] + [""]
    out = root / "index.md"
    new = "\n".join(lines)
    old = out.read_text(encoding="utf-8") if out.exists() else None
    if old != new:
        out.write_text(new, encoding="utf-8", newline="\n")
        return True
    return False


def cmd_index(root):
    changed = build_index(root)
    print(f"index: {'updated' if changed else 'ok (no change)'} ({root.resolve().name})")


def lint(root, verbose):
    files = md_files(root)
    existing = {p.relative_to(root).as_posix() for p in files}
    by_base = defaultdict(set)
    for r in existing:
        name = PurePosixPath(r).name
        by_base[name].add(r)
        by_base[name.rsplit(".", 1)[0]].add(r)
    problems = []
    for p in files:
        r = p.relative_to(root).as_posix()
        if PurePosixPath(r).name in ("CLAUDE.md", "AGENTS.md", "log.md"):
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        if PurePosixPath(r).name != "index.md":
            fm = frontmatter(text)
            if fm is None:
                problems.append((r, "no frontmatter"))
            else:
                for k in REQUIRED:
                    if not fm.get(k):
                        problems.append((r, f"frontmatter: missing {k}"))
                if fm.get("updated") and not re.match(r"^\d{4}-\d{2}-\d{2}$", fm["updated"]):
                    problems.append((r, f"frontmatter: bad updated {fm['updated']!r}"))
        body = re.sub(r"```.*?```", "", text, flags=re.S)
        d = str(PurePosixPath(r).parent)
        for m in LINK.finditer(body):
            tg = m.group(1).strip()
            if not tg:
                continue
            if "/" not in tg:
                ok = tg in by_base or tg.removesuffix(".md") in by_base
            else:
                ok = any(
                    c and (c in existing or c + ".md" in existing)
                    for c in (norm(d + "/" + tg), norm(tg))
                )
            if not ok:
                problems.append((r, f"broken link [[{tg}]]"))
    if not (root / "index.md").exists():
        problems.append((".", "index.md missing — run: kc index"))
    label = root.resolve().name
    if not problems:
        print(f"lint {label}: ok")
    else:
        kinds = defaultdict(int)
        for _, msg in problems:
            kinds[msg.split(" [[")[0].split(":")[0]] += 1
        detail = ", ".join(f"{v} {k}" for k, v in sorted(kinds.items(), key=lambda x: -x[1]))
        print(f"lint {label}: {len(problems)} problems ({detail})" + ("" if verbose else " — add -v for details"))
    if verbose:
        for r, msg in problems:
            print(f"  {r}: {msg}")
    return len(problems)


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    cmd, rest = argv[0], argv[1:]
    verbose = "-v" in rest
    rest = [a for a in rest if a != "-v"]
    root = Path(rest[0]).resolve() if rest else Path.cwd()
    if cmd == "index":
        cmd_index(root)
    elif cmd == "lint":
        lint(root, verbose)
    elif cmd == "check":
        cmd_index(root)
        lint(root, True)
    else:
        print(__doc__)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
